### ISSUE TITLE
ZenGarden

### ISSUE THREAD

**Issue by SkyWave2022** [Cubik65536/friends-api#4]
```json
{
    "title": "ZenGarden",
    "url": "https://www.zengarden.top",
    "avatar": "none(maybelater",
    "screenshot": "https://user-images.githubusercontent.com/86274592/165523579-e866c391-e28e-4774-bb82-a42a224873af.png",
    "description": "ZenGarden:给你一个平台，创造整个世界",
    "keywords": "Minecraft Server,ZenGarden"
}
```

我的友链页： https://www.zengarden.top/crazy_ones.html

**Comment by Qubik65536** [comment]
**有几个问题：**
1. 图片部分只放置 URL 即可
2. 你的友链页似乎是 404 的
3. 你的网站似乎有些功能不工作
4. 我们暂时不接受例如服务器组织等类型网站的加入
------
待这这些问题解决后我会重新考虑

**Comment by Qubik65536** [comment]
在你准备好之后可以重新打开这个 Issue

**Comment by SkyWave2022** [comment]
> 在你准备好之后可以重新打开这个 Issue

我们是完全公益的的❤

**Comment by SkyWave2022** [comment]
> 在你准备好之后可以重新打开这个 Issue

好的，我回去修改一下

**Comment by SkyWave2022** [comment]
目前网站还在建设之中

**Comment by SkyWave2022** [comment]
现在应该可以访问了

**Comment by SkyWave2022** [comment]
貌似服务器缓存刷新的有点慢( •̀ ω •́ )✧

**Comment by Qubik65536** [comment]
> > 在你准备好之后可以重新打开这个 Issue
> 
> 
> 
> 我们是完全公益的的❤

这点我懂，但是我认为个人博客不适合放置非博客作为友情链接。我也在计划运营一个纯公益 Minecraft 服务器，如果到那时你仍有兴趣的话我可以考虑互相增加友情链接
